version: '2'

services:
  spid-testenv-identityserver:
    build: identity-server/
    ports:
      - "9443:9443"

  spid-testenv-backoffice:
    build: backoffice/
    ports:
      - "8080:8080"
    volumes:
      - ./config.js:/spid-testenvironment/bo/backoffice/server/wso2/config.js
    environment:
      - NODE_ENV=development
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - spid-testenv-identityserver
